/******************************************************************************
* Each new term in the Fibonacci sequence is generated by adding the previous *
* two terms. By starting with 1 and 2, the first 10 terms will be:            *
*                                                                             *
* 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...                                      *
*                                                                             *
* By considering the terms in the Fibonacci sequence whose values do not      *
* exceed four million, find the sum of the even-valued terms.                 *
******************************************************************************/

/******************************************************************************
*                                   DEFINES                                   *
******************************************************************************/
#define PROBLEM_2_MAX_VAL 4000000
/******************************************************************************
*                                  INCLUDES                                   *
******************************************************************************/
#include "eulerProblems.h"
#include "eulerSolvers.h"
/******************************************************************************
*                             FUNCTION PROTOTYPES                             *
******************************************************************************/
static unsigned fibSum_even(unsigned max);
static inline void fib_next(unsigned* fn,unsigned* fn_1);
/******************************************************************************
*                            FUNCTION DEFINITIONS                             *
******************************************************************************/
/**
* Replaces fn and fn_1 with next value in fibbonacci sequence
**/
static inline void fib_next(unsigned* fn,unsigned* fn_1){
	unsigned temp = *fn+*fn_1;
	*fn_1 = *fn;
	*fn = temp;
}
/**
* Sums even numbered fibonacci numbers up to max fibbonaci term value
*
* Works off the principle that, Fx*k is divisible by Fx for all fibonacci
* numbers (thus every 3rd fibonacci number is divisible by 2)
**/
static unsigned fibSum_even(unsigned max){
	unsigned fn   = 2;
	unsigned fn_1 = 1;
	unsigned sum = 0;
	
	if(max < 2){
		return 0;
	}
	
	do{
		sum += fn;
		
		fib_next(&fn,&fn_1);
		fib_next(&fn,&fn_1);
		fib_next(&fn,&fn_1);
	}while(fn < max);
	
	return sum;
}
/**
* Solution for problem 2
**/
struct eulerSol euler_prob2(void){
	struct eulerSol sol = {U64};
	
	sol.val.u64 = fibSum_even(PROBLEM_2_MAX_VAL);
	
	return sol;
}